### ISSUE TITLE
Rename public structs

### ISSUE THREAD

**Issue by mathstuf** [tomhoule/graphql-client#101]
IMO, the types exposed by the crate have a bad "stutter" problem. It'd be much easier to just rename:

  - `GraphQLQuery` → `Query`
  - `GraphQLBody` → `Body`
  - `GraphQLResponse` → `Response`
  - `GraphQLError` → `Error`

collisions should be dealt with on the `use` side of things (e.g., a crate may rename them back to `GraphQL` prefixes, it may be easier to use a `Http` prefix, or possibly just use them scoped).

**Comment by tomhoule** [comment]
Yep it's reasonable. It's not a conscious decision, but I think the current names are aligning with what I read in the juniper and apollo-client codebases.

I need some more time (and maybe input from others) to think about it - let's gather the discussion in this issue.

**Comment by mathstuf** [comment]
For another example, see [this rename in the `log` crate](https://github.com/rust-lang-nursery/log/commit/d4748011fa9e7702653a80c5852f408f6bd4a3b5).

**Comment by scrogson** [comment]
I’m generally in favor of renaming.
