### ISSUE TITLE
Fix interface/fragment support

### ISSUE THREAD

**Issue by mathstuf** [tomhoule/graphql-client#113]
Currently fragment references on interfaces generates bad code. Instead of a struct with union `on` and the variants having fields, I get fields for each type as well as an `on` field. (This is when using #105.)

**Comment by tomhoule** [comment]
It should be possible to create a minimal query to reproduce the problem in the integrations test folder. I'll prioritize this above the rest when I have time to work on graphql-client (this weekend probably).

**Comment by tomhoule** [comment]
I opened a PR with a test to reproduce the problem: https://github.com/tomhoule/graphql-client/pull/153

Although apparently it's not even compiling, instead of generating bad code. Anyhow it needs to be fixed, I'll do this in priority.

**Comment by tomhoule** [comment]
Fixed by #153
