### ISSUE TITLE
Make cargo rerun if input files change

### ISSUE THREAD

**Issue by mathstuf** [tomhoule/graphql-client#117]
Currently this doesn't seem to be the case. I assume there is some API for it somewhere. A quick search shows nothing yet.

**Comment by tomhoule** [comment]
I don't know if there is an API, it's a bit problematic. I'll try to look into it.

**Comment by mathstuf** [comment]
Looks like [`Cargo.toml`](https://users.rust-lang.org/t/opening-files-in-proc-macros/11387/5) is what's supposed to be used. Probably worth a mention in the docs.

**Comment by tomhoule** [comment]
Oh I didn't know that. Yes that should be documented.

**Comment by tomhoule** [comment]
Putting this on the 0.5 milestone because it has to be documented.

**Comment by mathstuf** [comment]
It's worth mentioning that my attempt to do this in my project didn't work. See https://github.com/rust-lang/cargo/issues/6031#issuecomment-422160178.

**Comment by tomhoule** [comment]
This is now in the README, thanks for investigating!
