### ISSUE TITLE
Can not use __typename field

### ISSUE THREAD

**Issue by h-michael** [tomhoule/graphql-client#137]
I think we can use __typename with schema.graphql, but can not with schema.json.

This is sample query and schema.
https://gist.github.com/h-michael/4ffdc4c223719748706a5c4cb6ab94e7
https://github.com/octokit/graphql-schema/blob/master/schema.json

This query can receive response with github grapql api explore.

**Comment by h-michael** [comment]
Sorry this is not related with schema format.
I try to again wiht schema.graphql, but I get error again.

https://github.com/octokit/graphql-schema/blob/master/schema.graphql

**Comment by h-michael** [comment]
This query can receive response with github grapql api explore.

**Comment by mathstuf** [comment]
What's actually the issue here? I'm using `__typename` just fine in my queries (though it gets renamed to `typename` in the generated code).

**Comment by h-michael** [comment]
@mathstuf
Uhm, I can not do about my case.
If the schema is formated with graphql, can you use __type with the schema transformed with json format?

**Comment by mathstuf** [comment]
I was going by your reply that the schema format doesn't matter; [these queries](https://gitlab.kitware.com/utils/rust-ghostflow/blob/master/ghostflow-github/src/graphql/query.graphql) compile just fine.

**Comment by h-michael** [comment]
@mathstuf
Thank you to show me your codes.
I re-review my codes.

**Comment by h-michael** [comment]
This problem was found to be due to wrong definition of my query.
I solved it thanks to @mathstuf.
