### ISSUE TITLE
Document cargo doc --document-private-items in README

### ISSUE THREAD

**Issue by tomhoule** [tomhoule/graphql-client#145]

**Comment by h-michael** [comment]
@tomhoule 
Could you elaborate a little more on your intention of this issue?

**Comment by tomhoule** [comment]
Sorry I didn't reply earlier - there is a `--document-private-items` flag you can pass to `cargo doc` so the code generated by the `derive` is documented, even if it's private.

**Comment by tomhoule** [comment]
It's now in the README so I'll close this issue.
