### ISSUE TITLE
Run external benchmarks

### ISSUE THREAD

**Issue by LegNeato** [tomhoule/graphql-client#152]
We should see how we do on https://github.com/convoyinc/graphql-client-benchmarks

**Comment by tomhoule** [comment]
I didn't know these benchmarks - we definitely should! The first line of the readme says it focuses on the caching implementation of the clients, and we don't have that yet. But it's worth checking out.

**Comment by LegNeato** [comment]
Yeah, upon further reading it might be higher-level than this crate.
