### ISSUE TITLE
Support subscriptions

### ISSUE THREAD

**Issue by tomhoule** [tomhoule/graphql-client#3]
The serialization part shouldn't be any different from queries and mutations.

**Comment by tomhoule** [comment]
This was implemented in 0.2.0 :tada:

**Comment by dzcpy** [comment]
Is this feature fully supported? Like using websocket to subscribe server's events.

**Comment by tomhoule** [comment]
The code generation is supported — the transport is not, it is something you have to plug in.

**Comment by tomhoule** [comment]
Please open a new issue if you find something missing.
