### ISSUE TITLE
Think about custom scalars that aren't strings

### ISSUE THREAD

**Issue by tomhoule** [tomhoule/graphql-client#9]
I am not clear on whether the spec allows that.

**Comment by tomhoule** [comment]
After a new reading it seems that yes, it is allowed (it just says that custom scalars should have a string representation, presumably for allowing embedding them into JSON).

What is the best way to allow for maximum flexibility there?

If we have a custom scalar called `Bytes`, we could generate `type Bytes = Vec<u8>;` (with an annotation on the struct to say what `Bytes` corresponds to).

I think it would probably be better to leave that out, and allow users to inject `use` statements inside the generated module directly, that way you would define your `Bytes` (or `Date`, for example) scalar in another module, and inject an import for it. This seems more flexible.

**Comment by tomhoule** [comment]
Relevant section from the spec: https://github.com/facebook/graphql/blob/master/spec/Section%203%20--%20Type%20System.md#scalars

**Comment by xtian** [comment]
There is also an RFC to allow the serialization type of a custom scalar to be defined: https://github.com/facebook/graphql/pull/326

**Comment by tomhoule** [comment]
We should definitely support that when it makes it into the spec, thanks for the link!

**Comment by tomhoule** [comment]
Custom target types for custom scalars are implemented in #74

**Comment by tomhoule** [comment]
This is implemented, let's move the discussion on the RFC to #75
